packages:
  - '*/src'

catalog:
  '@slidev/cli': ^52.1.0
  '@slidev/client': ^52.1.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  '@unocss/preset-icons': ^66.3.3
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/skill-icons': ^1.2.0
  '@iconify-json/vscode-icons': ^1.2.23
  '@iconify/collections': ^1.0.558
  '@iconify/json': ^2.2.351
  'playwright-chromium': ^1.53.1
  'seedrandom': ^3.0.5
  'vis-timeline': ^7.7.4
  'vue': ^3.5.16
  '@types/seedrandom': ^3.0.8
  'unocss': ^66.3.3